### ISSUE TITLE
Korrektur A04_DataStructure

### ISSUE THREAD

**Issue by AnnaLotz** [kretschmerlea/EIA2#1]
Wo ist der Unterschied von "Look at character" und "check Charakter"?
Gut, dass der Typ des Inputs in den Kategorien gespeichert ist. Das gilt ja immer für eine gesamte Kategorie.
Der Code sieht gut aus. Es scheint aber, dass der Linter bei dir nicht läuft, sonst würde er dir in einigen Zeilen fehlende `;` oder `,` angezeigt werden. Schau mal, ob du unter den Extensions "TSLint" installiert und aktiviert hast.

P.S.: Sorry für's so späte Feedback

**Comment by AnnaLotz** [comment]
Was noch fehlt ist ein Attribut bei der Ausrüstung für das Gewicht. Sonst kann man am Ende kein Gesamt-Gewicht berechen.

**Comment by kretschmerlea** [comment]
Ich glaub mit "Look at" habe ich gemeint, dass man sehen kann, wie sich der Character entwickelt und mit "Check" am Ende nochmal überprüfen, ob alles so passt. KA wie viel Sinn das so macht, wenn ich drüber nachdenke...

Also ich habe gerade geschaut und ich denke tslint läuft, aber da könnten wir ja morgen im Praktikum nochmal schauen, vielleicht ist es ja nicht richtig installiert oder so.

Das mit dem Gewicht kann ich ja einfach ncoh ergänzen.
